# Generated by Django 4.2.1 on 2024-08-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Women2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('title3', models.CharField(max_length=255)),
                ('title4', models.CharField(max_length=255)),
                ('title5', models.CharField(max_length=255)),
                ('title6', models.CharField(max_length=255)),
                ('content1', models.CharField(max_length=255)),
                ('content2', models.CharField(max_length=255)),
                ('content3', models.CharField(max_length=255)),
                ('content4', models.CharField(max_length=255)),
                ('content5', models.CharField(max_length=255)),
                ('content6', models.CharField(max_length=255)),
                ('content7', models.CharField(max_length=255)),
                ('content8', models.CharField(max_length=255)),
                ('content9', models.CharField(max_length=255)),
                ('content10', models.CharField(max_length=255)),
                ('content11', models.CharField(max_length=255)),
                ('content12', models.CharField(max_length=255)),
                ('content13', models.CharField(max_length=255)),
                ('content14', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Страницы сайта',
                'verbose_name_plural': 'Страницы сайта',
            },
        ),
        migrations.RemoveField(
            model_name='women',
            name='cat',
        ),
        migrations.AlterField(
            model_name='women',
            name='title1',
            field=models.CharField(max_length=255),
        ),
    ]
