# Generated by Django 4.2.1 on 2024-08-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_women3_women4_alter_women_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Women5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('text1', models.TextField(blank=True)),
                ('text2', models.TextField(blank=True)),
                ('text3', models.TextField(blank=True)),
                ('title2', models.CharField(max_length=255)),
                ('card1', models.CharField(max_length=255)),
                ('card2', models.CharField(max_length=255)),
                ('card3', models.CharField(max_length=255)),
                ('text_card1', models.TextField(blank=True)),
                ('text_card2', models.TextField(blank=True)),
                ('text_card3', models.TextField(blank=True)),
                ('content1', models.CharField(max_length=255)),
                ('content2', models.CharField(max_length=255)),
                ('content3', models.CharField(max_length=255)),
                ('content4', models.CharField(max_length=255)),
                ('content5', models.CharField(max_length=255)),
                ('content6', models.CharField(max_length=255)),
                ('content7', models.CharField(max_length=255)),
                ('content8', models.CharField(max_length=255)),
                ('content9', models.CharField(max_length=255)),
                ('content10', models.CharField(max_length=255)),
                ('content11', models.CharField(max_length=255)),
                ('content12', models.CharField(max_length=255)),
                ('content13', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Достижение учеников',
                'verbose_name_plural': 'Страница сайта "Достижение учеников"',
            },
        ),
        migrations.DeleteModel(
            name='Women3',
        ),
    ]
