# Generated by Django 4.2.1 on 2024-08-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_women5_delete_women3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women5',
            name='content10',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='women5',
            name='content11',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='women5',
            name='content12',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='women5',
            name='content13',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='women5',
            name='content6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='women5',
            name='content7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='women5',
            name='content8',
            field=models.TextField(blank=True),
        ),
    ]
