# Generated by Django 4.2.1 on 2024-08-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_remove_women2_content10_remove_women2_content11_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Women6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('title3', models.CharField(max_length=255)),
                ('title4', models.CharField(max_length=255)),
                ('title5', models.CharField(max_length=255)),
                ('title6', models.CharField(max_length=255)),
                ('title7', models.CharField(max_length=255)),
                ('title8', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('title_blue', models.CharField(max_length=255)),
                ('title_blue_down', models.CharField(max_length=255)),
                ('title_white', models.CharField(max_length=255)),
                ('title_white_down', models.CharField(max_length=255)),
                ('title_blue_in', models.CharField(max_length=255)),
                ('title_blue_in_down1', models.CharField(max_length=255)),
                ('title_blue_in_down2', models.CharField(max_length=255)),
                ('title_blue_in_down3', models.CharField(max_length=255)),
                ('title_blue_in_down4', models.CharField(max_length=255)),
                ('title_blue_in_down5', models.CharField(max_length=255)),
                ('text_blue1', models.CharField(max_length=255)),
                ('text_blue2', models.CharField(max_length=255)),
                ('text_blue3', models.CharField(max_length=255)),
                ('text_blue4', models.CharField(max_length=255)),
                ('text_blue5', models.CharField(max_length=255)),
                ('text_blue6', models.CharField(max_length=255)),
                ('text1', models.TextField(blank=True)),
                ('text2', models.TextField(blank=True)),
                ('text3', models.TextField(blank=True)),
                ('text4', models.TextField(blank=True)),
                ('text5', models.TextField(blank=True)),
                ('text6', models.TextField(blank=True)),
                ('content1', models.CharField(max_length=255)),
                ('content2', models.CharField(max_length=255)),
                ('content3', models.CharField(max_length=255)),
                ('content4', models.CharField(max_length=255)),
                ('content5', models.CharField(max_length=255)),
                ('content6', models.TextField(blank=True)),
                ('content7', models.TextField(blank=True)),
                ('content8', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Олимпиады',
                'verbose_name_plural': 'Страница сайта "Олимпиады"',
            },
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'verbose_name': 'Олимпиады', 'verbose_name_plural': 'Страница сайта "Олимпиады"'},
        ),
    ]
