# Generated by Django 4.2.1 on 2024-08-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Форма обратной связи', 'verbose_name_plural': 'Формы обратной связи'},
        ),
    ]
